# Compares the MOM_parameters_doc.* files freshly generated by the double_gyre_smoke test
# (in ACTUAL_DIR) against the golden copies committed alongside this fixture (in EXPECTED_DIR).
#
# If a difference is expected (e.g. a parameter default changed intentionally), regenerate the
# golden files by copying ACTUAL_DIR/MOM_parameters_doc.* over EXPECTED_DIR/MOM_parameters_doc.*
# and committing the result.

set(DOC_FILES
  MOM_parameters_doc.all
  MOM_parameters_doc.debugging
  MOM_parameters_doc.layout
  MOM_parameters_doc.short
)

foreach(doc_file ${DOC_FILES})
  execute_process(
    COMMAND ${CMAKE_COMMAND} -E compare_files
            "${EXPECTED_DIR}/${doc_file}"
            "${ACTUAL_DIR}/${doc_file}"
    RESULT_VARIABLE files_differ
  )
  if(files_differ)
    message(FATAL_ERROR
      "${doc_file} does not match the golden copy in ${EXPECTED_DIR}. "
      "If this change is expected, regenerate the golden files from ${ACTUAL_DIR} and commit them.")
  endif()
endforeach()
