name: Clang Format

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write

jobs:
  format:
    name: Run Clang-Format and create PR
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install clang-format
        run: sudo apt-get update && sudo apt-get install -y clang-format && clang-format --version

      - name: Format code
        run: |
          find ./src ./config_src ./tests -type f \( -name '*.hpp' -o -name '*.h' -o -name '*.cpp' -o -name '*.cxx' -o -name '*.cc' -o -name '*.c' \) -exec clang-format -i {} +

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "Auto-format code using clang-format"
          title: "Auto-format code with clang-format"
          body: "This PR was generated automatically to apply clang-format changes."
          branch: "auto/clang-format"
          delete-branch: true